function renderContent(data) {
  // Hero Section
  document.getElementById('hero-status').innerHTML = `<span class="h-status-dot" aria-hidden="true"></span> ${data.hero.status}`;
  document.getElementById('hero-name1').textContent = data.hero.name1;
  document.getElementById('hero-name2').textContent = data.hero.name2;
  document.getElementById('hero-tagline').innerHTML = data.hero.tagline;
  const heroChips = document.getElementById('hero-chips');
  heroChips.innerHTML = ''; // Clear existing
  data.hero.chips.forEach(chip => {
    heroChips.innerHTML += `<div class="hchip"><span class="hchip-val">${chip.value}</span>&nbsp;${chip.label}</div>`;
  });
  const heroStats = document.getElementById('hero-stats');
  heroStats.innerHTML = ''; // Clear existing
  data.hero.stats.forEach(stat => {
    heroStats.innerHTML += `
      <div class="hstat">
        <div class="hstat-n" data-t="${stat.value}" data-s="${stat.suffix}">${stat.value}${stat.suffix}</div>
        <div class="hstat-l">${stat.label}</div>
      </div>`;
  });
  const heroCards = document.getElementById('hero-cards');
  heroCards.innerHTML = ''; // Clear existing
  data.hero.cards.forEach(card => {
    heroCards.innerHTML += `
      <div class="hcard">
        <div class="hc-label">${card.label}</div>
        <div class="hc-value">${card.value}</div>
        <div class="hc-sub">${card.sub}</div>
      </div>`;
  });

  // Marquee Section
  const marqueeInner = document.querySelector('.mq-inner');
  if (marqueeInner && data.marquee) {
    const marqueeContent = data.marquee.map(item => `<div class="mq-item"><span class="mq-t">${item}</span><span class="mq-sep"></span></div>`).join('');
    marqueeInner.innerHTML = marqueeContent + marqueeContent; // Duplicate for seamless loop
  }

  // Metrics Section
  const metricsRow = document.getElementById('metrics-row');
  metricsRow.innerHTML = ''; // Clear existing
  data.metrics.forEach(metric => {
    metricsRow.innerHTML += `
      <div class="metric" role="listitem">
        <div class="card-shine" aria-hidden="true"></div>
        <div class="metric-num" data-t="${metric.value}" data-s="${metric.suffix}">${metric.value}${metric.suffix}</div>
        <div class="metric-label">${metric.label}</div>
        <div class="metric-sub">${metric.sub}</div>
      </div>`;
  });

  // About Section
  const aboutBio = document.getElementById('about-bio');
  if(aboutBio) {
    aboutBio.innerHTML = ''; // Clear existing
    data.about.bio.forEach(p => {
      aboutBio.innerHTML += `<p>${p}</p>`;
    });
  }
  const aboutPhils = document.getElementById('about-philosophies');
  if(aboutPhils) {
    aboutPhils.innerHTML = ''; // Clear existing
    data.about.philosophies.forEach(phil => {
      let chipsHtml = '';
      if (phil.chips) {
        chipsHtml = `<div class="mini-chips">${phil.chips.map(c => `<span class="mc">${c}</span>`).join('')}</div>`;
      }
      aboutPhils.innerHTML += `
        <div class="phil">
          <div class="phil-h">${phil.title}</div>
          <p class="phil-p">${phil.text}</p>
          ${chipsHtml}
        </div>`;
    });
  }

  // Skills Section (PHASE 1 REDESIGN)
  const skillsGrid = document.getElementById('skills-grid');
  if (skillsGrid && data.skills) {
    skillsGrid.innerHTML = ''; // Clear existing
    const tiers = ['Core', 'Emerging Lead', 'Practitioner'];
    tiers.forEach(tier => {
      if (data.skills[tier]) {
        const tierEl = document.createElement('div');
        tierEl.className = 'skill-tier';
        
        const titleEl = document.createElement('h3');
        titleEl.className = 'skill-tier-title';
        titleEl.textContent = tier;
        tierEl.appendChild(titleEl);

        const tagsContainer = document.createElement('div');
        tagsContainer.className = 'skill-tags';
        
        data.skills[tier].forEach(skillGroup => {
          skillGroup.tags.forEach(tag => {
            const tagEl = document.createElement('span');
            tagEl.className = 'skill-tag';
            tagEl.textContent = tag;
            tagEl.dataset.tier = tier;
            tagsContainer.appendChild(tagEl);
          });
        });
        
        tierEl.appendChild(tagsContainer);
        skillsGrid.appendChild(tierEl);
      }
    });
  }

  // Experience Section
  const expTimeline = document.getElementById('experience-timeline');
  if(expTimeline) {
    expTimeline.innerHTML = ''; // Clear existing
    data.experience.forEach(job => {
      let highlightHtml = '';
      if(job.highlight) {
          highlightHtml = `<div class="tl-highlight">${job.highlight}</div>`;
      }
      expTimeline.innerHTML += `
        <div class="tl-item">
          <div class="tl-dot" aria-hidden="true"></div>
          <div class="tl-meta">
            <span class="tl-period">${job.period}</span>
            <span class="tl-co">${job.company}</span>
          </div>
          <h3 class="tl-role">${job.role}</h3>
          <div class="tl-stack">${job.stack}</div>
          ${highlightHtml}
          <div class="tl-bls">
            ${job.points.map(p => `<div class="tl-bl"><span class="tl-bl-dot">▸</span><span>${p}</span></div>`).join('')}
          </div>
        </div>`;
    });
  }

  // Projects Section
  const featuredProjects = document.getElementById('featured-projects');
  if(featuredProjects) {
    featuredProjects.innerHTML = ''; // Clear existing
    data.projects.featured.forEach(proj => {
      featuredProjects.innerHTML += `
        <article class="pf-card" data-fc="${proj.categories}">
          <div class="card-shine" aria-hidden="true"></div>
          <div class="feat-badge">★ Featured — Flagship</div>
          <div class="pfc-period">${proj.period}</div>
          <h3 class="pfc-name">${proj.name}</h3>
          <div class="pfc-sub">${proj.sub}</div>
          <p class="pfc-desc">${proj.desc}</p>
          <div class="metric-bar">${proj.metric}</div>
          <div class="tech-row">
            ${proj.tags.map(t => `<span class="tt">${t}</span>`).join('')}
          </div>
        </article>`;
    });
  }
  const regularProjects = document.getElementById('regular-projects');
  if(regularProjects) {
    regularProjects.innerHTML = ''; // Clear existing
    data.projects.regular.forEach(proj => {
      regularProjects.innerHTML += `
        <article class="pc r" data-rc="${proj.categories}">
          <div class="pc-top-line" aria-hidden="true"></div>
          <div class="card-shine" aria-hidden="true"></div>
          <div class="pbadge proto">${proj.badge}</div>
          <div class="pc-period">${proj.period}</div>
          <h3 class="pc-name">${proj.name}</h3>
          <div class="pc-tag">${proj.tag}</div>
          <p class="pc-body">${proj.body}</p>
          <div class="pc-metric">${proj.metric}</div>
          <div class="tech-row">
            ${proj.tags.map(t => `<span class="tt">${t}</span>`).join('')}
          </div>
        </article>`;
    });
  }

  // GenAI Section
  const genaiBody = document.getElementById('genai-body');
  if (genaiBody && data.genAI && data.genAI.body) {
    genaiBody.innerHTML = data.genAI.body.map(p => `<p>${p}</p>`).join('');
  }
  const genaiCallout = document.getElementById('genai-callout');
  if (genaiCallout && data.genAI && data.genAI.callout) {
    genaiCallout.innerHTML = `
      <div class="ai-callout-h">${data.genAI.callout.title}</div>
      <p>${data.genAI.callout.text}</p>`;
  }
  const genaiPillars = document.getElementById('genai-pillars');
  if (genaiPillars && data.genAI && data.genAI.pillars) {
    genaiPillars.innerHTML = ''; // Clear existing
    data.genAI.pillars.forEach((pillar, i) => {
      genaiPillars.innerHTML += `
        <div class="ai-pillar">
          <div class="card-shine" aria-hidden="true"></div>
          <div class="aip-num">${String(i + 1).padStart(2, '0')}</div>
          <div class="aip-title">${pillar.title}</div>
          <p class="aip-text">${pillar.text}</p>
        </div>`;
    });
  }

  // Theme Switcher
  const themePanel = document.getElementById('theme-panel');
  if (themePanel && data.themes) {
    const label = themePanel.querySelector('.tp-label');
    themePanel.innerHTML = ''; // Clear existing
    if(label) themePanel.appendChild(label); // Re-add label
    data.themes.forEach(theme => {
      const swatches = theme.colors.map(color => `<span class="theme-swatch" style="background:${color}"></span>`).join('');
      themePanel.innerHTML += `
        <button class="theme-btn" data-theme="${theme.id}" role="option">
          <span class="theme-swatches">${swatches}</span>
          <span><div class="theme-name">${theme.name}</div><div class="theme-desc">${theme.desc}</div></span>
        </button>`;
    });
  }
}


// ═══════════════════════════════════════
// THEMES (VELOCITY THEME APPLIED)
// ═══════════════════════════════════════
var THEMES = {
  'aurora': { /* This is now the "Velocity" theme */
    '--void':     '#0F1419',
    '--abyss':    '#0A0E12',
    '--base':     '#14191F',
    '--raised':   '#1A2027',
    '--lifted':   '#202730',
    '--border':   'rgba(139, 92, 246, .1)',
    '--border2':  'rgba(139, 92, 246, .2)',
    '--v':        '#8B5CF6',
    '--v2':       '#A78BFA',
    '--v3':       '#C4B5FD',
    '--c':        '#06B6D4',
    '--c2':       '#22D3EE',
    '--c3':       '#67E8F9',
    '--gold':     '#FBBF24',
    '--gold2':    '#FCD34D',
    '--v-g':      'rgba(139, 92, 246, .1)',
    '--v-b':      'rgba(139, 92, 246, .25)',
    '--v-glow':   'rgba(139, 92, 246, .4)',
    '--c-g':      'rgba(6, 182, 212, .1)',
    '--c-b':      'rgba(6, 182, 212, .25)',
    '--gold-g':   'rgba(251, 191, 36, .1)',
    '--gold-b':   'rgba(251, 191, 36, .25)',
    '--txt1':     '#F1F5F9',
    '--txt2':     '#94A3B8',
    '--txt3':     '#64748B',
    '--txt4':     '#475569',
    '--particle1':'#8B5CF6',
    '--particle2':'#06B6D4',
    '--particle3':'#FBBF24',
  },
  'neon-tokyo': {
    '--void':     '#000000',
    '--abyss':    '#030305',
    '--base':     '#060608',
    '--raised':   '#0C0C10',
    '--lifted':   '#111115',
    '--border':   'rgba(0,255,136,.07)',
    '--border2':  'rgba(0,255,136,.16)',
    '--v':        '#00CC6A',
    '--v2':       '#00FF88',
    '--v3':       '#7FFFBF',
    '--v-g':      'rgba(0,255,136,.07)',
    '--v-b':      'rgba(0,255,136,.2)',
    '--v-glow':   'rgba(0,255,136,.4)',
    '--c':        '#FF2D78',
    '--c2':       '#FF5C99',
    '--c3':       '#FFB3CC',
    '--c-g':      'rgba(255,45,120,.07)',
    '--c-b':      'rgba(255,45,120,.2)',
    '--gold':     '#00CFFF',
    '--gold2':    '#7FE7FF',
    '--gold-g':   'rgba(0,207,255,.07)',
    '--gold-b':   'rgba(0,207,255,.18)',
    '--em':       '#00FF88',
    '--txt1':     '#FFFFFF',
    '--txt2':     '#A0AEC0',
    '--txt3':     '#4A5568',
    '--txt4':     '#2D3748',
    '--particle1':'#00FF88',
    '--particle2':'#FF2D78',
    '--particle3':'#00CFFF',
  },
  'solaris': {
    '--void':     '#080402',
    '--abyss':    '#100A05',
    '--base':     '#180F08',
    '--raised':   '#24160D',
    '--lifted':   '#2E1D12',
    '--border':   'rgba(249,115,22,.07)',
    '--border2':  'rgba(249,115,22,.16)',
    '--v':        '#F97316',
    '--v2':       '#FB923C',
    '--v3':       '#FDBA74',
    '--v-g':      'rgba(249,115,22,.08)',
    '--v-b':      'rgba(249,115,22,.22)',
    '--v-glow':   'rgba(249,115,22,.4)',
    '--c':        '#EF4444',
    '--c2':       '#F87171',
    '--c3':       '#FCA5A5',
    '--c-g':      'rgba(239,68,68,.08)',
    '--c-b':      'rgba(239,68,68,.2)',
    '--gold':     '#FBBF24',
    '--gold2':    '#FCD34D',
    '--gold-g':   'rgba(251,191,36,.08)',
    '--gold-b':   'rgba(251,191,36,.18)',
    '--em':       '#FBBF24',
    '--txt1':     '#FFF7ED',
    '--txt2':     '#FED7AA',
    '--txt3':     '#B45309',
    '--txt4':     '#7C2D12',
    '--particle1':'#F97316',
    '--particle2':'#EF4444',
    '--particle3':'#FBBF24',
  },
  'oceanic': {
    '--void':     '#020609',
    '--abyss':    '#050C13',
    '--base':     '#08111C',
    '--raised':   '#0E1A2A',
    '--lifted':   '#132235',
    '--border':   'rgba(59,130,246,.07)',
    '--border2':  'rgba(59,130,246,.16)',
    '--v':        '#3B82F6',
    '--v2':       '#60A5FA',
    '--v3':       '#93C5FD',
    '--v-g':      'rgba(59,130,246,.08)',
    '--v-b':      'rgba(59,130,246,.22)',
    '--v-glow':   'rgba(59,130,246,.4)',
    '--c':        '#14B8A6',
    '--c2':       '#2DD4BF',
    '--c3':       '#5EEAD4',
    '--c-g':      'rgba(20,184,166,.08)',
    '--c-b':      'rgba(20,184,166,.2)',
    '--gold':     '#67E8F9',
    '--gold2':    '#A5F3FC',
    '--gold-g':   'rgba(103,232,249,.07)',
    '--gold-b':   'rgba(103,232,249,.15)',
    '--em':       '#2DD4BF',
    '--txt1':     '#F0F9FF',
    '--txt2':     '#7DD3FC',
    '--txt3':     '#0C4A6E',
    '--txt4':     '#082f49',
    '--particle1':'#3B82F6',
    '--particle2':'#14B8A6',
    '--particle3':'#67E8F9',
  },
  'jade': {
    '--void':     '#030806',
    '--abyss':    '#07100C',
    '--base':     '#0B1811',
    '--raised':   '#102319',
    '--lifted':   '#152E20',
    '--border':   'rgba(34,197,94,.07)',
    '--border2':  'rgba(34,197,94,.16)',
    '--v':        '#22C55E',
    '--v2':       '#4ADE80',
    '--v3':       '#86EFAC',
    '--v-g':      'rgba(34,197,94,.08)',
    '--v-b':      'rgba(34,197,94,.22)',
    '--v-glow':   'rgba(34,197,94,.4)',
    '--c':        '#84CC16',
    '--c2':       '#A3E635',
    '--c3':       '#BEF264',
    '--c-g':      'rgba(132,204,22,.08)',
    '--c-b':      'rgba(132,204,22,.2)',
    '--gold':     '#10B981',
    '--gold2':    '#34D399',
    '--gold-g':   'rgba(16,185,129,.08)',
    '--gold-b':   'rgba(16,185,129,.18)',
    '--em':       '#A3E635',
    '--txt1':     '#F7FEE7',
    '--txt2':     '#D9F99D',
    '--txt3':     '#3F6212',
    '--txt4':     '#1A2E05',
    '--particle1':'#4ADE80',
    '--particle2':'#A3E635',
    '--particle3':'#34D399',
  }
};

// Mesh gradient overrides per theme (injected as inline style on .mesh)
var MESH_GRADIENTS = {
  'aurora':     'rgba(139,92,246,.12),rgba(6,182,212,.09),rgba(251,191,36,.05)',
  'neon-tokyo': 'rgba(0,255,136,.1),rgba(255,45,120,.08),rgba(0,207,255,.05)',
  'solaris':    'rgba(249,115,22,.12),rgba(239,68,68,.09),rgba(251,191,36,.05)',
  'oceanic':    'rgba(59,130,246,.12),rgba(20,184,166,.09),rgba(103,232,249,.04)',
  'jade':       'rgba(34,197,94,.12),rgba(132,204,22,.09),rgba(16,185,129,.05)',
};

// Contact section bg overrides
var CONTACT_GRADIENTS = {
  'aurora':     'linear-gradient(135deg,#8B5CF6,#1e1b4b 50%,#0F1419)',
  'neon-tokyo': 'linear-gradient(135deg,#003820,#1a0030 50%,#000005)',
  'solaris':    'linear-gradient(135deg,#B45309,#7C2D12 50%,#080402)',
  'oceanic':    'linear-gradient(135deg,#0C4A6E,#082f49 50%,#020609)',
  'jade':       'linear-gradient(135deg,#166534,#1A2E05 50%,#030806)',
};

var currentTheme = 'aurora';

function applyTheme(name) {
  var theme = THEMES[name];
  if (!theme) {
    console.warn(`Theme "${name}" not found. Defaulting to 'aurora'.`);
    theme = THEMES['aurora'];
    name = 'aurora';
  }
  var root = document.documentElement;
  Object.keys(theme).forEach(function(k) {
    root.style.setProperty(k, theme[k]);
  });

  // Update mesh gradient
  var mesh = document.querySelector('.mesh');
  if (mesh && MESH_GRADIENTS[name]) {
    var c = MESH_GRADIENTS[name];
    var colors = c.split(',');
    mesh.style.background =
      'radial-gradient(ellipse 700px 600px at 80% 10%,'+colors[0]+',transparent),' +
      'radial-gradient(ellipse 600px 500px at 5% 70%,'+colors[1]+',transparent),' +
      'radial-gradient(ellipse 400px 400px at 50% 50%,'+colors[2]+',transparent),' +
      theme['--void'];
  }

  // Update contact gradient
  var cl = document.querySelector('.cl');
  if (cl && CONTACT_GRADIENTS[name]) {
    cl.style.background = CONTACT_GRADIENTS[name];
  }

  // Update AI callout
  var aiCallout = document.querySelector('.ai-callout');
  if (aiCallout) {
    if (name === 'neon-tokyo') {
      aiCallout.style.background = 'linear-gradient(135deg,#003820,#00CC6A)';
    } else if (name === 'solaris') {
      aiCallout.style.background = 'linear-gradient(135deg,#B45309,#F97316)';
    } else if (name === 'oceanic') {
      aiCallout.style.background = 'linear-gradient(135deg,#0C4A6E,#3B82F6)';
    } else if (name === 'jade') {
      aiCallout.style.background = 'linear-gradient(135deg,#166534,#22C55E)';
    } else { // Default to aurora
      aiCallout.style.background = 'linear-gradient(135deg,var(--v),#1e1b4b)';
    }
  }

  // Update palette preview dots
  var pDots = document.querySelectorAll('#palette-preview-dots .palette-dot');
  var p = [theme['--v2'], theme['--c2'], theme['--gold2']];
  pDots.forEach(function(d, i) { if (p[i]) d.style.background = p[i]; });

  // Update active state on buttons
  document.querySelectorAll('.theme-btn').forEach(function(b) {
    b.classList.toggle('active', b.dataset.theme === name);
  });

  currentTheme = name;
  localStorage.setItem('ns-theme', name);
}

function initThemeSwitcher() {
  var toggleBtn = document.getElementById('theme-toggle-btn');
  var panel = document.getElementById('theme-panel');
  if (!toggleBtn || !panel) return;

  toggleBtn.addEventListener('click', function() {
    var isOpen = panel.classList.toggle('open');
    toggleBtn.setAttribute('aria-expanded', isOpen);
  });

  // Close on outside click
  document.addEventListener('click', function(e) {
    if (!document.getElementById('theme-switcher').contains(e.target)) {
      panel.classList.remove('open');
      toggleBtn.setAttribute('aria-expanded', 'false');
    }
  });

  // Use event delegation for dynamically added theme buttons
  panel.addEventListener('click', function(e) {
    const btn = e.target.closest('.theme-btn');
    if (btn) {
      applyTheme(btn.dataset.theme);
      panel.classList.remove('open');
      toggleBtn.setAttribute('aria-expanded', 'false');
    }
  });

  // Restore saved theme
  var saved = localStorage.getItem('ns-theme');
  if (saved && THEMES[saved]) {
    applyTheme(saved);
  } else {
    applyTheme('aurora'); // Default to aurora
  }
}

// ═══════════════════════════════════════
// LOADER
// ═══════════════════════════════════════
document.addEventListener('DOMContentLoaded', function() {
    fetch('portfolio-data.json')
    .then(response => {
      if (!response.ok) {
        throw new Error('Network response was not ok ' + response.statusText);
      }
      return response.json();
    })
    .then(data => {
      renderContent(data);
      setTimeout(function() {
        var loader = document.getElementById('loader');
        if (loader) loader.classList.add('done');
        initAll();
      }, 100); // Reduced delay for faster perceived load
    })
    .catch(error => {
        console.error("Failed to load or render portfolio data:", error);
        // Optionally, display an error message to the user
        var loader = document.getElementById('loader');
        if (loader) {
            loader.innerHTML = '<div class="ldr-tag" style="animation:none;opacity:1;">Error loading content.</div>';
        }
    });
});
setTimeout(function() {
  var loader = document.getElementById('loader');
  if (loader && !loader.classList.contains('done')) {
    loader.classList.add('done');
  }
}, 3500);

function initAll() {
  initThemeSwitcher();
  initThree();
  initCursor();
  initNav();
  initScrollReveal();
  initCounters();
  initTilt();
  initMagnetic();
  initProjectFilters();
  initCopyBtns();
  initResumeViewer();
  initHamburger();
  initBackToTop();
}

// ... (rest of the functions remain the same)
// ... (initThree, initCursor, etc.)
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
// ...
- rest of the file content
